version: "3.8"

services:
  prod:
    container_name: prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_API_URL=https://localhost:9001/
      - REACT_APP_DEFAULT_IMAGE_VEHICLE_URL=https://t4.ftcdn.net/jpg/04/73/25/49/360_F_473254957_bxG9yf4ly7OBO5I0O5KABlN930GwaMQz.jpg
