export const COLORS = {
  // RED
  AUTO_MOREIRA_RED: "#d32f2f",
  AUTO_MOREIRA_ALTERNATIVE_RED: "#d84315",
  AUTO_MOREIRA_SIMPLE_LIGHT_RED: "#fbdfd6",
  // GREEN
  AUTO_MOREIRA_GREEN: "#2e7d32",
  AUTO_MOREIRA_ALTERNATIVE_GREEN: "#00c853",
  AUTO_MOREIRA_SIMPLE_LIGHT_GREEN: "#ddffe6",
  // BLUE
  AUTO_MOREIRA_BLUE: "#405a73",
  AUTO_MOREIRA_ALTERNATIVE_BLUE: "#2d3f51",
  AUTO_MOREIRA_SIMPLE_BLUE: "#0288d1",
  AUTO_MOREIRA_SIMPLE_LIGHT_BLUE: "#e3f2ff",
  AUTO_MOREIRA_SOLID_BLUE: "#2196f3",
  // YELLOW
  AUTO_MOREIRA_YELLOW: "#eeba17",
  AUTO_MOREIRA_ALTERNATIVE_YELLOW: "#ffc107",
  AUTO_MOREIRA_LIGHT_YELLOW: "#f5df9f",
  AUTO_MOREIRA_STRONG_YELLOW: "#f7bb05",
  // GREY
  AUTO_MOREIRA_GREY: "#c7c7c7",
  //ORANGE
  AUTO_MOREIRA_ORANGE: "#ff4d30"
};
